Rename PassaporteWeb to NexaasID
myfreecomm/passaporteweb-client-ruby pull request #18
Opened 2018-08-21 19:40 UTC by buiatte

2018-08-21 20:06 UTC, cacilhas requested changes

2018-08-21 20:06 UTC, cacilhas commented on README.md
> +NexaasID API docs: https://id.nexaas.com/static/docs/
Aqui é `Nexaas ID API docs`.

2018-08-21 20:06 UTC, cacilhas commented on README.md
> +# Invites another user to NexaasID on behalf of the current user
Sei que é apenas um comentário, mas aqui seria `Nexaas ID` também.

2018-08-21 20:06 UTC, cacilhas commented on lib/nexaas_id/configuration.rb
> +    @user_agent = "NexaasID Ruby Client v#{NexaasID::VERSION}"
`Nexaas ID Ruby Client`

2018-08-21 20:06 UTC, cacilhas commented on lib/nexaas_id/resources/profile.rb
> +# A wrapper to NexaasID's profile API
`Nexaas ID's profile API`

2018-08-21 20:06 UTC, cacilhas commented on lib/nexaas_id/resources/sign_up.rb
> +# A wrapper to NexaasID's sign up API
`Nexaas ID's sign up API`

2018-08-21 20:06 UTC, cacilhas commented on lib/nexaas_id/resources/widget.rb
> +# A wrapper to NexaasID's widget API
`Nexaas ID's widget API`

2018-08-21 20:34 UTC, buiatte commented
[ch16298]

2018-08-21 21:46 UTC, cacilhas approved these changes

2018-09-10 18:26 UTC, cacilhas commented
[nexaas-id-ruby-client PR #1](https://github.com/myfreecomm/nexaas-id-client-ruby/pull/1)

2018-09-10 18:26 UTC, closed without merging